name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.18 ]
        os: [ ubuntu-latest, macOS-latest ]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          args: --no-config --deadline=3m --disable-all --enable=deadcode  --enable=gocyclo --enable=varcheck --enable=errcheck --enable=ineffassign --enable=unconvert